#!/usr/bin/env bash
# End-to-end MCP integration test for paperclip-context-mcp.
#
# This script talks to the MCP server over stdio JSON-RPC. Before the MCP
# session it performs two read-only curl preflights (API connectivity and, when
# supplied, heartbeat-run status). It does not require jq.
#
# WARNING: the full test creates and mutates real Paperclip data in
# PAPERCLIP_COMPANY_ID. Run only against a disposable/test company.

set -uo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SERVER_ENTRY="$ROOT_DIR/dist/index.js"
MCP_PROTOCOL_VERSION="${MCP_PROTOCOL_VERSION:-2025-11-25}"
MCP_READ_TIMEOUT="${PAPERCLIP_TEST_MCP_TIMEOUT_SECONDS:-30}"
MAIN_INLINE_THRESHOLD="${PAPERCLIP_TEST_INLINE_THRESHOLD:-30000}"

PASS_COUNT=0
FAIL_COUNT=0
SKIP_COUNT=0
REQUEST_ID=0
LAST_RESPONSE=""
MCP_PID=""
MCP_OUT_FD=""
MCP_IN_FD=""
SERVER_STDERR=""
SERVER_TELEMETRY=""
MCP_PROTOCOL_IN_LOG=""
MCP_PROTOCOL_OUT_LOG=""
TEST_DIR=""
ISSUE_ID=""
CHECKOUT_ISSUE_ID=""
LARGE_ISSUE_ID=""
LARGE_SNAPSHOT_PATH=""
LONG_DESCRIPTION_WORDS=0
ISSUE_CHECKED_OUT=0
RUN_STATUS="unknown"
RUN_IS_LIVE=0

if (( BASH_VERSINFO[0] < 4 )); then
  printf 'ERROR: test.sh requires Bash 4+ (coproc is used). Current: %s\n' "$BASH_VERSION" >&2
  exit 2
fi

declare -A CALLED_TOOLS=()
declare -A SUCCESS_TOOLS=()

EXPECTED_TOOLS=(
  paperclip_context
  paperclip_inbox
  paperclip_issue
  paperclip_heartbeat_context
  paperclip_issues
  paperclip_issue_create
  paperclip_issue_update
  paperclip_issue_checkout
  paperclip_issue_release
  paperclip_comments
  paperclip_comment_add
  paperclip_documents
  paperclip_document
  paperclip_document_put
  paperclip_agents
  paperclip_raw
)

if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
  C_RESET=$'\033[0m'
  C_DIM=$'\033[2m'
  C_BLUE=$'\033[34m'
  C_GREEN=$'\033[32m'
  C_YELLOW=$'\033[33m'
  C_RED=$'\033[31m'
else
  C_RESET=''
  C_DIM=''
  C_BLUE=''
  C_GREEN=''
  C_YELLOW=''
  C_RED=''
fi

log()      { printf '%s[%s]%s %s\n' "$C_BLUE" "$(date '+%H:%M:%S')" "$C_RESET" "$*"; }
log_dim()  { printf '%s[%s] %s%s\n' "$C_DIM" "$(date '+%H:%M:%S')" "$*" "$C_RESET"; }
log_warn() { printf '%s[WARN]%s %s\n' "$C_YELLOW" "$C_RESET" "$*"; }
log_err()  { printf '%s[FAIL]%s %s\n' "$C_RED" "$C_RESET" "$*" >&2; }

pass() {
  PASS_COUNT=$((PASS_COUNT + 1))
  printf '%s[PASS]%s %s\n' "$C_GREEN" "$C_RESET" "$*"
}

fail() {
  FAIL_COUNT=$((FAIL_COUNT + 1))
  log_err "$*"
}

skip() {
  SKIP_COUNT=$((SKIP_COUNT + 1))
  printf '%s[SKIP]%s %s\n' "$C_YELLOW" "$C_RESET" "$*"
}

die() {
  log_err "$*"
  exit 2
}

json_escape() {
  local s="$1"
  s=${s//\\/\\\\}
  s=${s//\"/\\\"}
  s=${s//$'\n'/\\n}
  s=${s//$'\r'/\\r}
  s=${s//$'\t'/\\t}
  printf '%s' "$s"
}

json_string() {
  printf '"%s"' "$(json_escape "$1")"
}

response_has_protocol_error() {
  [[ "$1" == *'"error":{'* ]]
}

response_has_tool_error() {
  [[ "$1" == *'"isError":true'* ]]
}

response_preview() {
  local s="$1"
  local max="${2:-1600}"
  if (( ${#s} > max )); then
    printf '%s…' "${s:0:max}"
  else
    printf '%s' "$s"
  fi
}

extract_text_field_simple() {
  # Intended for compact ACK/path results generated by this MCP. It is not a
  # general JSON parser. These strings contain no embedded quote characters.
  local s="$1"
  local marker='"text":"'
  [[ "$s" == *"$marker"* ]] || return 1
  s="${s#*"$marker"}"
  printf '%s' "${s%%\"*}"
}

extract_created_ref() {
  local s="$1"
  [[ "$s" == *'Created '* ]] || return 1
  s="${s#*Created }"
  printf '%s' "${s%% *}"
}

require_env() {
  local name="$1"
  if [[ -z "${!name:-}" ]]; then
    die "Missing required environment variable: $name"
  fi
}

prepare_long_description() {
  # Build a payload that is guaranteed to cross the MCP's *rendered* token
  # threshold while keeping the HTTP request reasonably small. The estimator
  # counts lexical units at ~1.5 tokens each, so repeated short non-ASCII words
  # cross the default 30k threshold at roughly 20k words (~60-70 KiB UTF-8).
  #
  # PAPERCLIP_TEST_LONG_DESCRIPTION_WORDS can override the generated size when
  # testing a custom threshold or server request-body limit.
  local threshold="$1"
  local begin_marker="$2"
  local end_marker="$3"
  local fill=''

  if [[ -n "${PAPERCLIP_TEST_LONG_DESCRIPTION_WORDS:-}" ]]; then
    LONG_DESCRIPTION_WORDS="$PAPERCLIP_TEST_LONG_DESCRIPTION_WORDS"
  elif (( threshold > 0 )); then
    LONG_DESCRIPTION_WORDS=$(( (threshold * 2 + 2) / 3 + 2500 ))
  else
    LONG_DESCRIPTION_WORDS=22500
  fi

  if ! [[ "$LONG_DESCRIPTION_WORDS" =~ ^[0-9]+$ ]] || (( LONG_DESCRIPTION_WORDS < 1 )); then
    die "PAPERCLIP_TEST_LONG_DESCRIPTION_WORDS must be a positive integer"
  fi

  printf -v fill '%*s' "$LONG_DESCRIPTION_WORDS" ''
  fill="${fill// /é }"
  LONG_DESCRIPTION="${begin_marker}"$'\n'"${fill}"$'\n'"${end_marker}"
}

stop_server() {
  if [[ -n "$MCP_IN_FD" ]]; then
    eval "exec ${MCP_IN_FD}>&-" 2>/dev/null || true
    MCP_IN_FD=""
  fi
  if [[ -n "$MCP_OUT_FD" ]]; then
    eval "exec ${MCP_OUT_FD}<&-" 2>/dev/null || true
    MCP_OUT_FD=""
  fi
  if [[ -n "$MCP_PID" ]]; then
    if kill -0 "$MCP_PID" 2>/dev/null; then
      kill "$MCP_PID" 2>/dev/null || true
    fi
    wait "$MCP_PID" 2>/dev/null || true
    MCP_PID=""
  fi
}

cleanup() {
  stop_server
  if [[ -n "${TEST_DIR:-}" ]]; then
    log_dim "Integration-test logs kept at: $TEST_DIR"
  fi
}
trap cleanup EXIT INT TERM

start_server() {
  local threshold="$1"
  local label="$2"

  stop_server

  SERVER_STDERR="$TEST_DIR/${label}.server.stderr.log"
  SERVER_TELEMETRY="$TEST_DIR/${label}.telemetry.jsonl"
  MCP_PROTOCOL_IN_LOG="$TEST_DIR/${label}.mcp.stdin.jsonl"
  MCP_PROTOCOL_OUT_LOG="$TEST_DIR/${label}.mcp.stdout.jsonl"
  : > "$SERVER_STDERR"
  : > "$SERVER_TELEMETRY"
  : > "$MCP_PROTOCOL_IN_LOG"
  : > "$MCP_PROTOCOL_OUT_LOG"

  local headers_json="${PAPERCLIP_MCP_HEADERS_JSON:-}"
  if [[ -z "$headers_json" ]]; then
    headers_json='{"X-Paperclip-MCP-Integration-Test":"bash-test"}'
    log_dim "PAPERCLIP_MCP_HEADERS_JSON unset; injecting a harmless integration-test header for this server process."
  else
    log_dim "Using caller-provided PAPERCLIP_MCP_HEADERS_JSON (value intentionally not logged)."
  fi

  log "Starting MCP server ($label, inline threshold=$threshold estimated tokens)"

  coproc PC_MCP {
    PAPERCLIP_MCP_INLINE_TOKEN_THRESHOLD="$threshold" \
    PAPERCLIP_MCP_ARTIFACT_DIR="$TEST_DIR/artifacts" \
    PAPERCLIP_MCP_TELEMETRY=1 \
    PAPERCLIP_MCP_TELEMETRY_FILE="$SERVER_TELEMETRY" \
    PAPERCLIP_MCP_HEADERS_JSON="$headers_json" \
      node "$SERVER_ENTRY" 2>>"$SERVER_STDERR"
  }

  MCP_PID="$PC_MCP_PID"
  MCP_OUT_FD="${PC_MCP[0]}"
  MCP_IN_FD="${PC_MCP[1]}"

  local i
  for ((i = 0; i < 100; i++)); do
    if grep -Fq '"status":"started"' "$SERVER_STDERR" 2>/dev/null; then
      pass "MCP server started: $label"
      if grep -Eq '"custom_header_count":[1-9][0-9]*' "$SERVER_STDERR"; then
        pass "MCP server loaded one or more custom request headers ($label)"
      else
        log_warn "MCP startup reports custom_header_count=0; custom-header request path is not exercised in this session"
      fi
      return 0
    fi
    if ! kill -0 "$MCP_PID" 2>/dev/null; then
      fail "MCP server exited during startup ($label)"
      sed -n '1,160p' "$SERVER_STDERR" >&2 || true
      return 1
    fi
    sleep 0.05
  done

  fail "Timed out waiting for MCP startup marker ($label)"
  sed -n '1,160p' "$SERVER_STDERR" >&2 || true
  return 1
}

send_notification() {
  local method="$1"
  local params="${2:-}"
  if [[ -n "$params" ]]; then
    printf '{"jsonrpc":"2.0","method":%s,"params":%s}\n' \
      "$(json_string "$method")" "$params" >&${MCP_IN_FD}
  else
    printf '{"jsonrpc":"2.0","method":%s}\n' \
      "$(json_string "$method")" >&${MCP_IN_FD}
  fi
}

mcp_request() {
  local method="$1"
  local params="${2-}"
  [[ -n "$params" ]] || params='{}'
  local line

  REQUEST_ID=$((REQUEST_ID + 1))
  local id="$REQUEST_ID"

  local request_line
  printf -v request_line '{"jsonrpc":"2.0","id":%d,"method":%s,"params":%s}' \
    "$id" "$(json_string "$method")" "$params"
  printf '%s\n' "$request_line" >> "$MCP_PROTOCOL_IN_LOG"
  printf '%s\n' "$request_line" >&${MCP_IN_FD}

  while true; do
    if ! IFS= read -r -t "$MCP_READ_TIMEOUT" line <&${MCP_OUT_FD}; then
      fail "Timed out waiting ${MCP_READ_TIMEOUT}s for MCP response to $method (request $id)"
      if [[ -n "$MCP_PID" ]] && ! kill -0 "$MCP_PID" 2>/dev/null; then
        log_err "MCP process is no longer running."
      fi
      sed -n '1,220p' "$SERVER_STDERR" >&2 || true
      LAST_RESPONSE=""
      return 1
    fi

    printf '%s\n' "$line" >> "$MCP_PROTOCOL_OUT_LOG"

    # Requests are sequential; ignore any non-response protocol messages until
    # the response carrying this request id arrives.
    if [[ "$line" == *"\"id\":$id"* ]]; then
      LAST_RESPONSE="$line"
      return 0
    fi
  done
}

initialize_mcp() {
  local params
  printf -v params '{"protocolVersion":%s,"capabilities":{},"clientInfo":{"name":"paperclip-context-mcp-bash-test","version":"1.0"}}' \
    "$(json_string "$MCP_PROTOCOL_VERSION")"

  if ! mcp_request initialize "$params"; then
    return 1
  fi
  if response_has_protocol_error "$LAST_RESPONSE"; then
    fail "MCP initialize returned protocol error: $(response_preview "$LAST_RESPONSE")"
    return 1
  fi

  send_notification notifications/initialized
  pass "MCP initialize handshake"
  return 0
}

tool_call() {
  local name="$1"
  local args="${2-}"
  [[ -n "$args" ]] || args='{}'
  local params
  CALLED_TOOLS["$name"]=1

  printf -v params '{"name":%s,"arguments":%s}' "$(json_string "$name")" "$args"
  mcp_request tools/call "$params"
}

run_tool_ok() {
  local label="$1"
  local name="$2"
  local args="${3-}"
  [[ -n "$args" ]] || args='{}'

  log "Tool: $name — $label"
  if ! tool_call "$name" "$args"; then
    fail "$name transport call failed — $label"
    return 1
  fi
  if response_has_protocol_error "$LAST_RESPONSE"; then
    fail "$name protocol error — $label: $(response_preview "$LAST_RESPONSE")"
    return 1
  fi
  if response_has_tool_error "$LAST_RESPONSE"; then
    fail "$name returned isError=true — $label: $(response_preview "$LAST_RESPONSE")"
    return 1
  fi

  SUCCESS_TOOLS["$name"]=1
  pass "$name — $label"
  return 0
}

run_tool_expected_error() {
  local label="$1"
  local name="$2"
  local args="${3-}"
  [[ -n "$args" ]] || args='{}'

  log "Tool (expected error): $name — $label"
  if ! tool_call "$name" "$args"; then
    fail "$name transport failed while testing expected error — $label"
    return 1
  fi
  if response_has_protocol_error "$LAST_RESPONSE"; then
    fail "$name produced protocol error rather than tool error — $label: $(response_preview "$LAST_RESPONSE")"
    return 1
  fi
  if ! response_has_tool_error "$LAST_RESPONSE"; then
    fail "$name unexpectedly succeeded — $label: $(response_preview "$LAST_RESPONSE")"
    return 1
  fi
  pass "$name correctly rejected invalid request — $label"
  return 0
}

assert_tool_catalog() {
  log "Listing MCP tools"
  if ! mcp_request tools/list '{}'; then
    return 1
  fi
  if response_has_protocol_error "$LAST_RESPONSE"; then
    fail "tools/list returned protocol error: $(response_preview "$LAST_RESPONSE")"
    return 1
  fi

  local tool
  local missing=0
  for tool in "${EXPECTED_TOOLS[@]}"; do
    if [[ "$LAST_RESPONSE" == *"$tool"* ]]; then
      pass "registered tool: $tool"
    else
      fail "missing registered tool: $tool"
      missing=1
    fi
  done
  return "$missing"
}

assert_telemetry_operation() {
  local file="$1"
  local op="$2"
  if grep -Fq "\"operation\":\"$op\"" "$file"; then
    pass "telemetry contains operation: $op"
    return 0
  fi
  fail "telemetry missing operation: $op"
  return 1
}


# Build a curl header file from PAPERCLIP_MCP_HEADERS_JSON without printing
# values or putting Cloudflare service-token secrets in curl's argv. Node is
# already required by the MCP and is only used here as a strict JSON decoder.
write_curl_header_file() {
  local out_file="$1"
  : > "$out_file"
  chmod 0600 "$out_file" 2>/dev/null || true

  if [[ -n "${PAPERCLIP_MCP_HEADERS_JSON:-}" ]]; then
    if ! PAPERCLIP_MCP_HEADERS_JSON="$PAPERCLIP_MCP_HEADERS_JSON" node - <<'NODE' >> "$out_file"; then
const raw = process.env.PAPERCLIP_MCP_HEADERS_JSON ?? '';
let parsed;
try {
  parsed = JSON.parse(raw);
} catch (error) {
  const message = error instanceof Error ? error.message : String(error);
  process.stderr.write(`Invalid PAPERCLIP_MCP_HEADERS_JSON: ${message}\n`);
  process.exit(2);
}
if (parsed === null || Array.isArray(parsed) || typeof parsed !== 'object') {
  process.stderr.write('PAPERCLIP_MCP_HEADERS_JSON must be a JSON object.\n');
  process.exit(2);
}
for (const [name, value] of Object.entries(parsed)) {
  if (typeof value !== 'string') {
    process.stderr.write(`Custom header ${name} must have a string value.\n`);
    process.exit(2);
  }
  if (!name.trim() || /[\r\n:]/.test(name) || /[\r\n]/.test(value)) {
    process.stderr.write(`Custom header ${JSON.stringify(name)} is not safe for an HTTP header file.\n`);
    process.exit(2);
  }
  const lower = name.toLowerCase();
  if (lower === 'authorization' || lower === 'x-paperclip-run-id') continue;
  process.stdout.write(`${name}: ${value}\n`);
}
NODE
      return 1
    fi
  fi

  # Paperclip identity is adapter-owned and applied after custom headers by the
  # TypeScript client. Mirror that behavior in curl.
  printf 'Authorization: Bearer %s\n' "$PAPERCLIP_API_KEY" >> "$out_file"
  printf 'Accept: application/json, text/plain;q=0.9, */*;q=0.1\n' >> "$out_file"
}

paperclip_preflight_url() {
  local base="${PAPERCLIP_API_URL%/}"
  if [[ "$base" == */api ]]; then
    printf '%s/companies/%s/issues?limit=1' "$base" "$PAPERCLIP_COMPANY_ID"
  else
    printf '%s/api/companies/%s/issues?limit=1' "$base" "$PAPERCLIP_COMPANY_ID"
  fi
}

api_connectivity_preflight() {
  command -v curl >/dev/null 2>&1 || die "curl is required for the API connectivity preflight"

  local url status body_file headers_file request_headers_file
  url="$(paperclip_preflight_url)"
  body_file="$TEST_DIR/api-preflight.body"
  headers_file="$TEST_DIR/api-preflight.headers"
  request_headers_file="$TEST_DIR/api-preflight.request.headers"
  : > "$body_file"
  : > "$headers_file"

  if ! write_curl_header_file "$request_headers_file"; then
    fail "Could not prepare custom headers for API preflight"
    return 1
  fi

  log "Preflight: Paperclip API connectivity via curl"
  log_dim "GET $url"
  log_dim "Request-header values are redacted; redirects are intentionally NOT followed."

  if ! status="$(curl \
    --silent \
    --show-error \
    --connect-timeout "${PAPERCLIP_TEST_CURL_CONNECT_TIMEOUT_SECONDS:-10}" \
    --max-time "${PAPERCLIP_TEST_CURL_TIMEOUT_SECONDS:-30}" \
    --dump-header "$headers_file" \
    --output "$body_file" \
    --write-out '%{http_code}' \
    --header "@$request_headers_file" \
    "$url")"; then
    fail "curl could not reach Paperclip API"
    log_err "Inspect response headers: $headers_file"
    log_err "Inspect response body: $body_file"
    return 1
  fi

  if [[ "$status" =~ ^2[0-9][0-9]$ ]]; then
    pass "Paperclip API connectivity (HTTP $status)"
    return 0
  fi

  fail "Paperclip API connectivity returned HTTP $status"
  log_err "Inspect response headers: $headers_file"
  log_err "Inspect response body: $body_file"
  if [[ -s "$body_file" ]]; then
    log_err "Response preview: $(LC_ALL=C head -c 1200 "$body_file" | tr '\n' ' ')"
  fi
  return 1
}


paperclip_run_url() {
  local base="${PAPERCLIP_API_URL%/}"
  if [[ "$base" == */api ]]; then
    printf '%s/heartbeat-runs/%s' "$base" "$PAPERCLIP_RUN_ID"
  else
    printf '%s/api/heartbeat-runs/%s' "$base" "$PAPERCLIP_RUN_ID"
  fi
}

extract_json_string_field_file() {
  local file="$1"
  local key="$2"
  LC_ALL=C grep -Eo '"'"$key"'"[[:space:]]*:[[:space:]]*"[^"]*"' "$file" 2>/dev/null \
    | head -n 1 \
    | sed -E 's/^[^:]+:[[:space:]]*"([^"]*)"$/\1/'
}

heartbeat_run_preflight() {
  local url http_status body_file headers_file request_headers_file
  url="$(paperclip_run_url)"
  body_file="$TEST_DIR/run-preflight.body"
  headers_file="$TEST_DIR/run-preflight.headers"
  request_headers_file="$TEST_DIR/run-preflight.request.headers"
  : > "$body_file"
  : > "$headers_file"

  if ! write_curl_header_file "$request_headers_file"; then
    log_warn "Could not prepare headers for heartbeat-run preflight; run liveness will be unknown"
    return 0
  fi

  log "Preflight: heartbeat-run attribution/liveness"
  log_dim "GET $url"

  if ! http_status="$(curl \
    --silent \
    --show-error \
    --connect-timeout "${PAPERCLIP_TEST_CURL_CONNECT_TIMEOUT_SECONDS:-10}" \
    --max-time "${PAPERCLIP_TEST_CURL_TIMEOUT_SECONDS:-30}" \
    --dump-header "$headers_file" \
    --output "$body_file" \
    --write-out '%{http_code}' \
    --header "@$request_headers_file" \
    "$url")"; then
    log_warn "Could not read heartbeat run; live ownership tests will be treated as unavailable"
    return 0
  fi

  if [[ ! "$http_status" =~ ^2[0-9][0-9]$ ]]; then
    log_warn "Heartbeat run lookup returned HTTP $http_status; live ownership tests will be treated as unavailable"
    log_dim "Inspect: $body_file"
    return 0
  fi

  RUN_STATUS="$(extract_json_string_field_file "$body_file" status || true)"
  local run_agent run_company
  run_agent="$(extract_json_string_field_file "$body_file" agentId || true)"
  run_company="$(extract_json_string_field_file "$body_file" companyId || true)"

  if [[ -n "$run_agent" && "$run_agent" != "$PAPERCLIP_AGENT_ID" ]]; then
    fail "PAPERCLIP_RUN_ID belongs to agent $run_agent, not PAPERCLIP_AGENT_ID=$PAPERCLIP_AGENT_ID"
  fi
  if [[ -n "$run_company" && "$run_company" != "$PAPERCLIP_COMPANY_ID" ]]; then
    fail "PAPERCLIP_RUN_ID belongs to company $run_company, not PAPERCLIP_COMPANY_ID=$PAPERCLIP_COMPANY_ID"
  fi

  if [[ -z "$RUN_STATUS" ]]; then
    RUN_STATUS="unknown"
    log_warn "Could not extract heartbeat run status; ownership-sensitive lifecycle checks will not be assumed live"
    return 0
  fi

  case "$RUN_STATUS" in
    succeeded|interrupted|failed|cancelled|timed_out)
      RUN_IS_LIVE=0
      log_warn "Heartbeat run is terminal: $RUN_STATUS"
      log_warn "Paperclip may clear checkout/execution locks owned by a terminal run before the next protected mutation."
      log_warn "The suite will still exercise every MCP tool, but will not require checkout→update/release ownership semantics."
      ;;
    *)
      RUN_IS_LIVE=1
      pass "heartbeat run is non-terminal: $RUN_STATUS"
      ;;
  esac
}

# ---- Preflight ------------------------------------------------------------

log "Paperclip Context MCP integration test"
log_warn "This test CREATES and MUTATES data in PAPERCLIP_COMPANY_ID. Use a disposable/test company."

if [[ "${PAPERCLIP_TEST_ALLOW_WRITES:-0}" != "1" ]]; then
  die "Set PAPERCLIP_TEST_ALLOW_WRITES=1 to confirm the target company is disposable."
fi

for name in \
  PAPERCLIP_API_URL \
  PAPERCLIP_API_KEY \
  PAPERCLIP_COMPANY_ID \
  PAPERCLIP_AGENT_ID \
  PAPERCLIP_RUN_ID; do
  require_env "$name"
done

log_dim "API URL: $PAPERCLIP_API_URL"
log_dim "Company: $PAPERCLIP_COMPANY_ID"
log_dim "Agent: $PAPERCLIP_AGENT_ID"
log_dim "Run: $PAPERCLIP_RUN_ID"
log_dim "API key: present (redacted)"
if [[ -n "${PAPERCLIP_MCP_HEADERS_JSON:-}" ]]; then
  log_dim "Custom request headers: configured (redacted)"
else
  log_dim "Custom request headers: test script will inject one harmless X-Paperclip-MCP-Integration-Test header"
fi

TEST_DIR="$(mktemp -d "${TMPDIR:-/tmp}/paperclip-context-mcp-test.XXXXXX")"
log_dim "Test work directory: $TEST_DIR"

if [[ "${PAPERCLIP_TEST_SKIP_BUILD:-0}" != "1" ]]; then
  if command -v pnpm >/dev/null 2>&1; then
    log "Building TypeScript"
    if (cd "$ROOT_DIR" && pnpm run build); then
      pass "TypeScript build"
    else
      die "TypeScript build failed; integration tests cannot continue."
    fi
  elif [[ -f "$SERVER_ENTRY" ]]; then
    log_warn "pnpm not found; using existing dist/index.js"
  else
    die "pnpm is not installed and dist/index.js is missing."
  fi
else
  log_warn "PAPERCLIP_TEST_SKIP_BUILD=1; skipping build"
fi

[[ -f "$SERVER_ENTRY" ]] || die "Missing built server: $SERVER_ENTRY"
command -v node >/dev/null 2>&1 || die "node is required"

api_connectivity_preflight || die "Paperclip API preflight failed; MCP tests were not started."
heartbeat_run_preflight

# ---- Main MCP session -----------------------------------------------------

start_server "$MAIN_INLINE_THRESHOLD" main || die "Could not start MCP server"
initialize_mcp || die "Could not initialize MCP session"
assert_tool_catalog || true

# Runtime-only read.
run_tool_ok "runtime environment" paperclip_context '{}' || true

# Agent reads: list and the current agent branch.
run_tool_ok "company roster" paperclip_agents '{}' || true
printf -v ARGS '{"id":%s}' "$(json_string "$PAPERCLIP_AGENT_ID")"
run_tool_ok "current agent by id" paperclip_agents "$ARGS" || true

# Collection read with no filters: this intentionally exercises the semantics
# that paperclip_issues means the company issue collection, not all_fields.
run_tool_ok "all visible company issues, no filters" paperclip_issues '{}' || true

# Create the primary fixture. Keep it out of in_progress while exercising
# ordinary writes so a manually supplied terminal heartbeat run does not turn
# Paperclip's run-ownership cleanup into a false-negative MCP failure.
STAMP="$(date -u '+%Y%m%dT%H%M%SZ')-$$"
TEST_TITLE="MCP integration test $STAMP"
TEST_DESCRIPTION="Created by paperclip-context-mcp/test.sh. Safe to inspect or delete after the test."
printf -v ARGS '{"title":%s,"description":%s,"status":"todo","priority":"medium"}' \
  "$(json_string "$TEST_TITLE")" "$(json_string "$TEST_DESCRIPTION")"

if run_tool_ok "create primary fixture issue" paperclip_issue_create "$ARGS"; then
  ISSUE_ID="$(extract_created_ref "$LAST_RESPONSE" || true)"
else
  die "Primary fixture issue creation failed; dependent tool tests cannot continue."
fi

if [[ -z "$ISSUE_ID" || "$ISSUE_ID" == "issue" ]]; then
  die "Could not extract created issue identifier/id from MCP acknowledgement: $(response_preview "$LAST_RESPONSE")"
fi
log "Primary fixture issue: $ISSUE_ID"

# Same endpoint, two renderer modes.
printf -v ARGS '{"id":%s}' "$(json_string "$ISSUE_ID")"
if run_tool_ok "compact issue renderer" paperclip_issue "$ARGS"; then
  if [[ "$LAST_RESPONSE" == *'"text":"# '* || "$LAST_RESPONSE" == *'"text":"#'* ]]; then
    pass "small compact issue is delivered inline under the ${MAIN_INLINE_THRESHOLD}-token threshold"
  else
    fail "small compact issue did not look like inline Markdown: $(response_preview "$LAST_RESPONSE")"
  fi
fi
printf -v ARGS '{"id":%s,"all_fields":true}' "$(json_string "$ISSUE_ID")"
run_tool_ok "expanded fields from same issue endpoint" paperclip_issue "$ARGS" || true

# Real production-threshold overflow test. A dedicated idle issue receives a
# description large enough to exceed MAIN_INLINE_THRESHOLD after compact
# Markdown rendering. We verify both sides of the contract:
#   1. the mutation that sets the huge description still returns only a tiny ACK;
#   2. a subsequent read returns only a snapshot path, while the complete
#      description is present in the immutable file on disk.
LARGE_TITLE="MCP large-description integration test $STAMP"
LARGE_DESC_BEGIN="MCP-LARGE-DESCRIPTION-BEGIN-$STAMP"
LARGE_DESC_END="MCP-LARGE-DESCRIPTION-END-$STAMP"
printf -v ARGS '{"title":%s,"description":%s,"status":"todo","priority":"low"}' \
  "$(json_string "$LARGE_TITLE")" \
  "$(json_string "Short bootstrap description; the integration test replaces this with an oversized payload.")"
if run_tool_ok "create large-description fixture issue" paperclip_issue_create "$ARGS"; then
  LARGE_ISSUE_ID="$(extract_created_ref "$LAST_RESPONSE" || true)"
else
  LARGE_ISSUE_ID=""
fi

if [[ -z "$LARGE_ISSUE_ID" || "$LARGE_ISSUE_ID" == "issue" ]]; then
  fail "Could not create/extract large-description fixture; real threshold test cannot continue"
else
  log "Large-description fixture issue: $LARGE_ISSUE_ID"
  prepare_long_description "$MAIN_INLINE_THRESHOLD" "$LARGE_DESC_BEGIN" "$LARGE_DESC_END"
  LONG_LEXICAL_ESTIMATE=$(( (LONG_DESCRIPTION_WORDS * 3 + 1) / 2 ))
  log_dim "Large description uses $LONG_DESCRIPTION_WORDS repeated words (~$LONG_LEXICAL_ESTIMATE lexical-token estimate before Markdown overhead)."

  printf -v ARGS '{"id":%s,"description":%s}' \
    "$(json_string "$LARGE_ISSUE_ID")" \
    "$(json_string "$LONG_DESCRIPTION")"
  if run_tool_ok "set oversized task description; mutation must remain compact" paperclip_issue_update "$ARGS"; then
    if [[ "$LAST_RESPONSE" != *"$LARGE_DESC_BEGIN"* && "$LAST_RESPONSE" != *"$LARGE_DESC_END"* && ${#LAST_RESPONSE} -lt 4096 ]]; then
      pass "oversized mutation response does not echo task description into model context"
    else
      fail "oversized mutation leaked description content or returned an unexpectedly large MCP result: $(response_preview "$LAST_RESPONSE" 800)"
    fi

    printf -v ARGS '{"id":%s}' "$(json_string "$LARGE_ISSUE_ID")"
    if run_tool_ok "read oversized task description at production threshold" paperclip_issue "$ARGS"; then
      LARGE_READ_RESPONSE="$LAST_RESPONSE"
      LARGE_SNAPSHOT_PATH="$(extract_text_field_simple "$LARGE_READ_RESPONSE" || true)"

      if [[ "$LARGE_READ_RESPONSE" != *"$LARGE_DESC_BEGIN"* && "$LARGE_READ_RESPONSE" != *"$LARGE_DESC_END"* && ${#LARGE_READ_RESPONSE} -lt 4096 ]]; then
        pass "oversized issue content is not returned inline to the model"
      else
        fail "oversized issue read leaked description content or returned an unexpectedly large MCP result: $(response_preview "$LARGE_READ_RESPONSE" 800)"
      fi

      if [[ -n "$LARGE_SNAPSHOT_PATH" && -f "$LARGE_SNAPSHOT_PATH" ]]; then
        pass "production-threshold issue read returned an existing snapshot path: $LARGE_SNAPSHOT_PATH"
      else
        fail "production-threshold issue read did not return an existing snapshot path: ${LARGE_SNAPSHOT_PATH:-<empty>}"
      fi

      if [[ -n "$LARGE_SNAPSHOT_PATH" ]] && grep -Fq "$LARGE_DESC_BEGIN" "$LARGE_SNAPSHOT_PATH" 2>/dev/null \
        && grep -Fq "$LARGE_DESC_END" "$LARGE_SNAPSHOT_PATH" 2>/dev/null; then
        pass "oversized task description is fully materialized in the snapshot"
      else
        fail "oversized snapshot is missing the task-description sentinel(s)"
      fi

      if [[ -n "$LARGE_SNAPSHOT_PATH" && -f "$LARGE_SNAPSHOT_PATH" ]]; then
        LARGE_SNAPSHOT_BYTES="$(wc -c < "$LARGE_SNAPSHOT_PATH" | tr -d '[:space:]')"
        if [[ "$LARGE_SNAPSHOT_BYTES" =~ ^[0-9]+$ ]] && (( LARGE_SNAPSHOT_BYTES > 50000 )); then
          pass "oversized snapshot contains substantial payload data (${LARGE_SNAPSHOT_BYTES} bytes)"
        else
          fail "oversized snapshot is unexpectedly small (${LARGE_SNAPSHOT_BYTES:-unknown} bytes)"
        fi
      fi

      LARGE_TELEMETRY_LINE="$(grep -F "\"artifact_path\":\"$LARGE_SNAPSHOT_PATH\"" "$SERVER_TELEMETRY" 2>/dev/null | tail -n 1 || true)"
      if [[ -n "$LARGE_TELEMETRY_LINE" && "$LARGE_TELEMETRY_LINE" == *'"delivery":"snapshot"'* ]]; then
        pass "production-threshold telemetry records snapshot delivery"
      else
        fail "production-threshold snapshot telemetry entry missing"
      fi

      LARGE_RENDERED_TOKEN_ESTIMATE="$(printf '%s' "$LARGE_TELEMETRY_LINE" | sed -nE 's/.*"rendered_tokens_estimate":([0-9]+).*/\1/p')"
      if [[ "$LARGE_RENDERED_TOKEN_ESTIMATE" =~ ^[0-9]+$ ]] && (( LARGE_RENDERED_TOKEN_ESTIMATE > MAIN_INLINE_THRESHOLD )); then
        pass "rendered oversized issue exceeds configured threshold (${LARGE_RENDERED_TOKEN_ESTIMATE} > ${MAIN_INLINE_THRESHOLD})"
      else
        fail "telemetry did not confirm rendered issue exceeded threshold (estimate=${LARGE_RENDERED_TOKEN_ESTIMATE:-unknown}, threshold=$MAIN_INLINE_THRESHOLD)"
      fi
    fi
  fi

  # Reduce retained test data after the assertion. This also confirms that a
  # later mutation does not depend on editing the snapshot file.
  printf -v ARGS '{"id":%s,"description":%s,"status":"done","comment":%s}' \
    "$(json_string "$LARGE_ISSUE_ID")" \
    "$(json_string "Large-description snapshot test completed; oversized payload removed during cleanup.")" \
    "$(json_string "paperclip-context-mcp oversized-description integration test completed")"
  run_tool_ok "clean up large-description fixture issue" paperclip_issue_update "$ARGS" || true
  unset LONG_DESCRIPTION
fi

# Update while todo/unassigned. This validates the tool and compact mutation
# response independently of checkout-run ownership semantics.
printf -v ARGS '{"id":%s,"priority":"high","description":%s}' \
  "$(json_string "$ISSUE_ID")" \
  "$(json_string "Updated by integration test $STAMP. Mutation response should be compact.")"
run_tool_ok "update todo fixture issue" paperclip_issue_update "$ARGS" || true

# Dedicated comment mutation + read.
COMMENT_BODY="Integration test comment $STAMP"
printf -v ARGS '{"issue_id":%s,"body":%s}' \
  "$(json_string "$ISSUE_ID")" "$(json_string "$COMMENT_BODY")"
run_tool_ok "add comment" paperclip_comment_add "$ARGS" || true

printf -v ARGS '{"issue_id":%s,"limit":50}' "$(json_string "$ISSUE_ID")"
run_tool_ok "read comments" paperclip_comments "$ARGS" || true

# Document write + collection + single-document read while issue is still idle.
DOC_KEY="mcp-integration-$STAMP"
DOC_KEY="${DOC_KEY,,}"
DOC_BODY="# MCP integration document\n\nCreated by test.sh at $STAMP.\n\nThis document validates document PUT/read/list through MCP."
printf -v ARGS '{"issue_id":%s,"key":%s,"title":%s,"body":%s,"change_summary":%s}' \
  "$(json_string "$ISSUE_ID")" \
  "$(json_string "$DOC_KEY")" \
  "$(json_string "MCP integration $STAMP")" \
  "$(json_string "$DOC_BODY")" \
  "$(json_string "Created by integration test")"
run_tool_ok "create document on idle issue" paperclip_document_put "$ARGS" || true

printf -v ARGS '{"issue_id":%s}' "$(json_string "$ISSUE_ID")"
run_tool_ok "list issue documents" paperclip_documents "$ARGS" || true

printf -v ARGS '{"issue_id":%s,"key":%s}' \
  "$(json_string "$ISSUE_ID")" "$(json_string "$DOC_KEY")"
run_tool_ok "read one document" paperclip_document "$ARGS" || true

# Exercise release independently of a live checkout. Paperclip's release route
# is valid for idle issues too; on todo it simply clears any assignment/locks
# without requiring checkout-run ownership. A live-run lifecycle is tested
# separately below when the supplied heartbeat run is non-terminal.
printf -v ARGS '{"id":%s}' "$(json_string "$ISSUE_ID")"
run_tool_ok "release idle fixture issue" paperclip_issue_release "$ARGS" || true

# Filtered collection read. The title is unique to this test run.
printf -v ARGS '{"q":%s,"limit":10}' "$(json_string "$TEST_TITLE")"
run_tool_ok "filtered issue search" paperclip_issues "$ARGS" || true

# Raw fallback: one real successful request and one local safety rejection.
printf -v RAW_PATH '/api/issues/%s' "$ISSUE_ID"
printf -v ARGS '{"method":"GET","path":%s,"all_fields":false}' "$(json_string "$RAW_PATH")"
run_tool_ok "same-origin raw GET fallback" paperclip_raw "$ARGS" || true
run_tool_expected_error "external URL rejected before request" paperclip_raw \
  '{"method":"GET","path":"https://example.com/should-not-run"}' || true

# Close the primary fixture before testing checkout. This keeps the primary
# fixture clean even when PAPERCLIP_RUN_ID is historical/terminal.
printf -v ARGS '{"id":%s,"status":"done","comment":%s}' \
  "$(json_string "$ISSUE_ID")" \
  "$(json_string "paperclip-context-mcp integration test $STAMP primary fixture completed")"
run_tool_ok "close primary fixture issue" paperclip_issue_update "$ARGS" || true

# A second fixture is dedicated to checkout/heartbeat/inbox semantics. Checkout
# requires a run id. If the supplied run is terminal, current Paperclip servers
# can accept checkout but clear its lock before the next protected mutation;
# therefore the guarded post-checkout lifecycle is only asserted for live runs.
CHECKOUT_TITLE="MCP checkout integration test $STAMP"
printf -v ARGS '{"title":%s,"description":%s,"status":"todo","priority":"low"}' \
  "$(json_string "$CHECKOUT_TITLE")" \
  "$(json_string "Dedicated checkout fixture created by paperclip-context-mcp/test.sh.")"
if run_tool_ok "create checkout fixture issue" paperclip_issue_create "$ARGS"; then
  CHECKOUT_ISSUE_ID="$(extract_created_ref "$LAST_RESPONSE" || true)"
else
  CHECKOUT_ISSUE_ID=""
fi

if [[ -z "$CHECKOUT_ISSUE_ID" || "$CHECKOUT_ISSUE_ID" == "issue" ]]; then
  fail "Could not create/extract checkout fixture; checkout workflow tests cannot continue"
else
  log "Checkout fixture issue: $CHECKOUT_ISSUE_ID"
  printf -v ARGS '{"id":%s}' "$(json_string "$CHECKOUT_ISSUE_ID")"
  if run_tool_ok "checkout dedicated fixture issue" paperclip_issue_checkout "$ARGS"; then
    ISSUE_CHECKED_OUT=1
  fi

  printf -v ARGS '{"id":%s}' "$(json_string "$CHECKOUT_ISSUE_ID")"
  run_tool_ok "explicit heartbeat-context endpoint" paperclip_heartbeat_context "$ARGS" || true
  run_tool_ok "agent inbox after checkout" paperclip_inbox '{}' || true

  if (( ISSUE_CHECKED_OUT == 1 && RUN_IS_LIVE == 1 )); then
    printf -v ARGS '{"id":%s,"priority":"medium"}' "$(json_string "$CHECKOUT_ISSUE_ID")"
    run_tool_ok "protected update owned by live checkout run" paperclip_issue_update "$ARGS" || true

    printf -v ARGS '{"id":%s}' "$(json_string "$CHECKOUT_ISSUE_ID")"
    if run_tool_ok "release live checkout" paperclip_issue_release "$ARGS"; then
      ISSUE_CHECKED_OUT=0
    fi

    printf -v ARGS '{"id":%s,"status":"done","comment":%s}' \
      "$(json_string "$CHECKOUT_ISSUE_ID")" \
      "$(json_string "paperclip-context-mcp live checkout integration completed")"
    run_tool_ok "close checkout fixture after live release" paperclip_issue_update "$ARGS" || true
  elif (( ISSUE_CHECKED_OUT == 1 )); then
    skip "checkout→protected-update ownership assertion: PAPERCLIP_RUN_ID status is $RUN_STATUS"
    skip "live checkout release assertion: PAPERCLIP_RUN_ID status is $RUN_STATUS"
    log_warn "Checkout fixture $CHECKOUT_ISSUE_ID may remain in_progress because a terminal/unknown run cannot safely own the lock."
  fi
fi

# ---- Main-session telemetry checks ---------------------------------------

log "Checking main-session telemetry"
for op in \
  context.get \
  agents.list \
  agent.get \
  issues.list \
  issue.create \
  issue.get \
  issue.checkout \
  issue.heartbeat_context \
  inbox.get \
  issue.update \
  comment.add \
  comments.list \
  document.put \
  documents.list \
  document.get \
  raw.get \
  issue.release; do
  assert_telemetry_operation "$SERVER_TELEMETRY" "$op" || true
done

# Verify issue.get did not silently switch to heartbeat-context when
# all_fields=true. This is intentionally a grep-level invariant check so the
# test stays Bash-only.
ISSUE_GET_LINES="$TEST_DIR/issue-get.telemetry.txt"
grep -F '"operation":"issue.get"' "$SERVER_TELEMETRY" > "$ISSUE_GET_LINES" || true
if [[ -s "$ISSUE_GET_LINES" ]] && ! grep -Fq 'heartbeat-context' "$ISSUE_GET_LINES"; then
  pass "paperclip_issue telemetry stays on /api/issues/:id for compact and all_fields calls"
else
  fail "paperclip_issue telemetry unexpectedly references heartbeat-context"
fi

if grep -Fq '"delivery":"ack"' "$SERVER_TELEMETRY"; then
  pass "mutation telemetry records compact acknowledgement delivery"
else
  fail "no mutation acknowledgement telemetry found"
fi

stop_server

# ---- Forced-snapshot session --------------------------------------------
# The production default is 30k estimated tokens. Generating >30k real test
# content would make this integration test expensive and brittle, so we test
# the exact same delivery branch deterministically with threshold=0.

start_server 0 snapshot || die "Could not start forced-snapshot MCP server"
initialize_mcp || die "Could not initialize forced-snapshot MCP session"

printf -v ARGS '{"id":%s}' "$(json_string "$ISSUE_ID")"
if run_tool_ok "forced snapshot delivery, first read" paperclip_issue "$ARGS"; then
  SNAPSHOT_ONE="$(extract_text_field_simple "$LAST_RESPONSE" || true)"
else
  SNAPSHOT_ONE=""
fi

if [[ -n "$SNAPSHOT_ONE" && -f "$SNAPSHOT_ONE" ]]; then
  pass "snapshot path exists: $SNAPSHOT_ONE"
else
  fail "forced snapshot call did not return an existing file path: ${SNAPSHOT_ONE:-<empty>}"
fi

if [[ -n "$SNAPSHOT_ONE" ]] && head -n 1 "$SNAPSHOT_ONE" 2>/dev/null | grep -Fq 'Paperclip snapshot @'; then
  pass "snapshot contains Paperclip read-only/freshness header"
else
  fail "snapshot header missing or unreadable"
fi

if [[ -n "$SNAPSHOT_ONE" && ! -w "$SNAPSHOT_ONE" ]]; then
  pass "snapshot is not writable by the test process"
else
  log_warn "snapshot appears writable to this process; exact permission behavior can differ for privileged users/filesystems"
fi

if run_tool_ok "forced snapshot delivery, second read" paperclip_issue "$ARGS"; then
  SNAPSHOT_TWO="$(extract_text_field_simple "$LAST_RESPONSE" || true)"
else
  SNAPSHOT_TWO=""
fi

if [[ -n "$SNAPSHOT_ONE" && -n "$SNAPSHOT_TWO" && "$SNAPSHOT_ONE" != "$SNAPSHOT_TWO" ]]; then
  pass "repeated reads produce unique immutable snapshot paths"
else
  fail "repeated reads reused the same snapshot path"
fi

if grep -Fq '"delivery":"snapshot"' "$SERVER_TELEMETRY"; then
  pass "telemetry records snapshot delivery"
else
  fail "snapshot telemetry entry missing"
fi

stop_server

# ---- Coverage summary ----------------------------------------------------

log "Checking successful invocation coverage for every registered tool"
for tool in "${EXPECTED_TOOLS[@]}"; do
  if [[ -n "${SUCCESS_TOOLS[$tool]:-}" ]]; then
    pass "tool successfully exercised: $tool"
  else
    fail "tool never completed successfully: $tool"
  fi
done

printf '\n'
printf '%sIntegration summary%s\n' "$C_BLUE" "$C_RESET"
printf '  Passed: %d\n' "$PASS_COUNT"
printf '  Failed: %d\n' "$FAIL_COUNT"
printf '  Skipped: %d\n' "$SKIP_COUNT"
printf '  Primary fixture: %s\n' "${ISSUE_ID:-<not-created>}"
printf '  Checkout fixture: %s\n' "${CHECKOUT_ISSUE_ID:-<not-created>}"
printf '  Large-description fixture: %s\n' "${LARGE_ISSUE_ID:-<not-created>}"
printf '  Heartbeat run status: %s\n' "$RUN_STATUS"
printf '  Heartbeat run treated as live: %s\n' "$RUN_IS_LIVE"
printf '  Logs/artifacts: %s\n' "$TEST_DIR"
printf '\n'

if (( FAIL_COUNT > 0 )); then
  log_err "Integration test finished with $FAIL_COUNT failure(s)."
  exit 1
fi

printf '%sAll integration checks passed.%s\n' "$C_GREEN" "$C_RESET"
exit 0
